version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=courtyard_test
      - MYSQL_USER=test
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_PASSWORD=12345678
    volumes:
      - type: volume
        source: mysqlData
        target: /var/lib/mysql

volumes:
  mysqlData:
