export const loggerTopic = {
  SERVER: 'SERVER',
  DATABASE: 'DATABASE',
  PASSPORT: 'PASSPORT',
  CATEGORY: 'CATEGORY',
  REGION: 'REGION',
  USER: 'USER',
  IMGUR: 'IMGUR',
  RESTAURANT: 'RESTAURANT',
  CUISINE: 'CUISINE',
  CART: 'CART'
} as const;
